# Generated by Django 5.1.7 on 2025-03-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
